// Copyright 2009 Anh Hai Trinh. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Implements the faithful sieve of Eratosthenes.

// References:
// 	<http://www.cs.hmc.edu/~oneill/papers/Sieve-JFP.pdf>
// 	<http://en.literateprograms.org/Sieve_of_Eratosthenes_(Haskell)>

// This program will print all primes <= n, where n := flag.Arg(0).
// If the flag -n is given, it will print the nth prime only.

package main

import (
	"container/heap"
	"container/vector"
	"flag"
	"fmt"
	"math"
	"os"
	"runtime"
	"strconv"
)

var nth = flag.Bool("n", false, "print the nth prime only")
var nCPU = flag.Int("ncpu", 1, "number of CPUs to use")

// Wheel to quickly generate numbers coprime to 2, 3, 5 and 7.
// Starting from 13, we successively add wheel[i] to get 17, 19, 23, ...
var wheel = []int{
	4, 2, 4, 6, 2, 6, 4, 2, 4, 6, 6, 2, 6, 4, 2, 6, 4, 6, 8, 4, 2, 4, 2, 4, 8,
	6, 4, 6, 2, 4, 6, 2, 6, 6, 4, 2, 4, 6, 2, 6, 4, 2, 4, 2, 10, 2, 10, 2,
}

// Return a chan int of values (n + k * wheel[i]) for successive i.
func spin(n, k, i, bufsize int) chan int {
	out := make(chan int, bufsize)
	go func() {
		for {
			for ; i < 48; i++ {
				out <- n
				n += k * wheel[i]
			}
			i = 0
		}
	}()
	return out
}

// Return a chan of numbers coprime to 2, 3, 5 and 7, starting from 13.
// coprime2357() -> 13, 17, 19, 23, 25, 31, 35, 37, 41, 47, ...
func coprime2357() chan int { return spin(13, 1, 0, 750) }

// Map (p % 210) to a corresponding wheel position.
// A prime number can only be one of these value (mod 210).
var wheelpos = map[int]int{
	1: 46, 11: 47, 13: 0, 17: 1, 19: 2, 23: 3, 29: 4, 31: 5, 37: 6, 41: 7,
	43: 8, 47: 9, 53: 10, 59: 11, 61: 12, 67: 13, 71: 14, 73: 15, 79: 16,
	83: 17, 89: 18, 97: 19, 101: 20, 103: 21, 107: 22, 109: 23, 113: 24,
	121: 25, 127: 26, 131: 27, 137: 28, 139: 29, 143: 30, 149: 31, 151: 32,
	157: 33, 163: 34, 167: 35, 169: 36, 173: 37, 179: 38, 181: 39, 187: 40,
	191: 41, 193: 42, 197: 43, 199: 44, 209: 45,
}

// Return a chan of multiples of a prime p that are relative prime
// to 2, 3, 5 and 7, starting from (p * p).
// multiples(11) -> 121, 143, 187, 209, 253, 319, 341, 407, 451, 473, ...
// multiples(13) -> 169, 221, 247, 299, 377, 403, 481, 533, 559, 611, ...
func multiples(p int) chan int { return spin(p*p, p, wheelpos[p%210], 50) }

// Given a channel of known primes, return a channel of all composites to be eliminated
// by creating and merging channels of primes' multiples.
func mergeMultiples(primes chan int) chan int {
	out := make(chan int, 500)
	go func() {
		// Since the channel of known primes comes in increasing order, the
		// heads of the channels of multiples are sorted.  We use a heap and
		// keep popping out the minimum head between multiples generated by
		// a pool of primes until it is greater than the head of the next
		// prime multiple channel, in which case we add that channel into
		// the heap and ask for the next prime.
		h := NewPeekChHeap()
		min := 143
		for {
			m := multiples(<-primes)
			head := <-m
			for min < head {
				out <- min
				minchan := heap.Pop(h).(*PeekCh)
				min = minchan.head
				minchan.head = <-minchan.ch
				heap.Push(h, minchan)
			}
			for min == head {
				minchan := heap.Pop(h).(*PeekCh)
				min = minchan.head
				minchan.head = <-minchan.ch
				heap.Push(h, minchan)
			}
			out <- head
			heap.Push(h, &PeekCh{<-m, m})
		}
	}()
	return out
}

// Peekable chan int
type PeekCh struct {
	head int
	ch   chan int
}

// Heap of PeekCh, sorting by heads
type PeekChHeap struct {
	heads *vector.IntVector
	chs   *vector.Vector
}

func NewPeekChHeap() *PeekChHeap {
	h := new(PeekChHeap)
	h.heads = new(vector.IntVector)
	h.chs = new(vector.Vector)
	return h
}

func (h *PeekChHeap) Push(x interface{}) {
	h.heads.Push(x.(*PeekCh).head)
	h.chs.Push(x.(*PeekCh).ch)
}

func (h *PeekChHeap) Pop() interface{} {
	return &PeekCh{h.heads.Pop(), h.chs.Pop().(chan int)}
}

func (h *PeekChHeap) Len() int { return h.heads.Len() }

func (h *PeekChHeap) Less(i, j int) bool { return h.heads.Less(i, j) }

func (h *PeekChHeap) Swap(i, j int) {
	h.heads.Swap(i, j)
	h.chs.Swap(i, j)
}

// Return a chan int of primes.
// Attempt to receive more than n primes from the returned channel will soon deadlock.
func Primes(n int) chan int {
	out := make(chan int, 100)

	primes := make(chan int, n)
	// We need non-blocking send to this or we'll deadlock, since in order to
	// generate the nth prime we only need multiples of primes ≤ sqrt(prime(n)).
	// Thus, mergeMultiples() will receive from this channel much slower than
	// Primes() are sending to it, making the buffer grows.

	go func() {
		out <- 2
		out <- 3
		out <- 5
		out <- 7
		out <- 11
		primes <- 11
		composites := mergeMultiples(primes)
		candidates := coprime2357()
		p := <-candidates
		for {
			c := <-composites
			for p < c {
				primes <- p
				out <- p
				p = <-candidates
			}
			if p == c {
				p = <-candidates
			}
		}
	}()
	return out
}

// Return a chan int of primes.
// Attempt to receive primes ≥ n from the returned channel will soon deadlock.
func Sieve(n int) chan int { return Primes(primePi(n)) }

// Overestimate the number of primes ≤ n for all n ≤ 2^31-1
// using the Prime Number Theorem.
func primePi(n int) int {
	x := float64(n)
	return int(x/math.Log(x) + math.Pow(x, 0.72505))
}

func main() {
	flag.Parse()
	n, err := strconv.Atoi(flag.Arg(0))
	if err != nil {
		fmt.Fprintln(os.Stderr, "bad argument")
		os.Exit(1)
	}
	runtime.GOMAXPROCS(*nCPU)
	if *nth {
		primes := Primes(n)
		for i := 1; i < n; i++ {
			<-primes
		}
		fmt.Println(<-primes)
	} else {
		primes := Sieve(n)
		for {
			p := <-primes
			if p <= n {
				fmt.Println(p)
			} else {
				return
			}
		}
	}
}
